[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
async-stream = "0.3"
axum = "0.8"
bytes = "1"
clap = { version = "4.5", features = ["derive"] }
conduit-core = { version = "0.1.0", path = "crates/core" }
conduit-proxy = { version = "0.1.0", path = "crates/proxy" }
conduit-storage = { version = "0.1.0", path = "crates/storage" }
futures-util = "0.3"
http-body-util = "0.1"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "stream"] }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
toml = "1"
tower = { version = "0.5", features = ["util"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.22", features = ["v7"] }

[workspace.lints.clippy]
all = { level = "deny" }

[workspace.lints.rust]
warnings = { level = "deny" }
