[package]
name = "conduit-storage"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
conduit-core.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
