[package]
name = "valohai-conduit"
version.workspace = true
edition.workspace = true

[[bin]]
name = "conduit"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
conduit-core.workspace = true
conduit-proxy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
