[package]
name = "conduit-tui"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
chrono-humanize.workspace = true
conduit-core.workspace = true
crossterm.workspace = true
serde_json.workspace = true
ratatui.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
